package com.infodesire.tablestream;

import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'lars' at '13.06.14 10:39' with Gradle 1.12
 *
 * @author lars, @date 13.06.14 10:39
 */
public class MainTest {
    @Test 
    public void testSomeLibraryMethod() {
    }
}
