/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'lars' at '13.06.14 10:39' with Gradle 1.12
 *
 * @author lars, @date 13.06.14 10:39
 */

package com.infodesire.tablestream;

public class Main {
    public boolean someLibraryMethod() {
        return true;
    }
}
